spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to Bank loan related local APIs"
  contactDetails:
    name: "Charles Babbage - Quality Assurance Lead"
    email: "contato@charlesbabbage.qa.br"
  onCallSupport:
    - (+55) 031 95874-4444
    - (+55) 031 0800-1234